CREATE TABLE IF NOT EXISTS dart.km_overseas_sec_list_dec (
    _ts timestamptz NOT NULL,
    접수번호 VARCHAR(14),
    법인구분 CHAR(1),
    고유번호 VARCHAR(8),
    회사명 VARCHAR(100),
    상장예정보통주수 BIGINT,
    상장예정기타주수 BIGINT,
    보통주식총수 BIGINT,
    기타주식총수 BIGINT,
    공모방법_신주발행 BIGINT,
    공모방법_구주매출 BIGINT,
    신주발행목적 TEXT,
    원주상장수 BIGINT,
    DR상장수 BIGINT,
    상장거래소 VARCHAR(100),
    해외상장목적 TEXT,
    상장예정일자 DATE,
    이사회결의일 DATE,
    사사외이사참석수 INT,
    사외이사불참수 INT,
    감사위원참석여부 VARCAHR(255),
    PRIMARY KEY (접수번호) 
);