CREATE TABLE IF NOT EXISTS dart.br_othcorp_inv (
    _ts timestamptz NOT NULL,
    사업연도 SMALLINT NOT NULL,
    보고서코드 SMALLINT NOT NULL,
    접수번호 VARCHAR(14) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    법인구분 CHAR(1),
    회사명 VARCHAR(255),
    법인명 VARCHAR(255),
    최초취득일자 VARCHAR(255),
    출자목적 VARCHAR(255),
    최초취득금액 BIGINT,
    기초수량 BIGINT,
    기초지분율 VARCHAR(255),
    기초장부가액 BIGINT,
    증감수량 BIGINT,
    증감금액 BIGINT,
    증감평가손 BIGINT,
    기말수량 BIGINT,
    기말지분율 VARCHAR(255),
    기말장부가 BIGINT,
    최근사업년_총자산 BIGINT,
    최근사업년_당기순이익 BIGINT,
    PRIMARY KEY (접수번호, 법인명)
);