CREATE TABLE IF NOT EXISTS dart.km_acqsn_tgb (
    _ts timestamptz NOT NULL,
    접수번호 CHAR(14) NOT NULL,
    법인구분 CHAR(1) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    회사명 VARCHAR(300) NOT NULL,
    자산구분 VARCHAR(100),
    자산명 TEXT,
    양수금액 BIGINT,
    자산총액 BIGINT,
    자산총액대비비율 DECIMAL(5,2),
    양수목적 VARCHAR(300),
    양수영향 TEXT,
    계약체결일 DATE,
    양수기준일 DATE,
    등기예정일 DATE,
    거래상대회사명 VARCHAR(300),
    거래상대자본금 BIGINT,
    거래상대주요사업 VARCHAR(300),
    거래상대소재지 VARCHAR(300),
    거래상대회사와관계 VARCHAR(300),
    거래대금지급 TEXT,
    외부평가여부 VARCHAR(10),
    외부평가근거및사유 VARCHAR(300),
    외부평가기관명칭 VARCHAR(300),
    외부평가기간 VARCHAR(300),
    외부평가의견 VARCHAR(300),
    주총특별결의여부 VARCHAR(10),
    주총예정일자 DATE,
    주식매수청구권행사요건 VARCHAR(300),
    주식매수청구권매수예정가 BIGINT,
    주식매수청구권행사관련사항 VARCHAR(300),
    주식매수청구권지급관련사항 VARCHAR(300),
    주식매수청구권제한관련 VARCHAR(300),
    주식매수청구권계약에미치는효력 VARCHAR(300),
    이사회결의일 DATE,
    사외이사참석수 SMALLINT,
    사외이사불참수 SMALLINT,
    감사위원참석여부 VARCHAR(10),
    공정위신고대상여부 VARCHAR(10),
    풋옵션등계약체결여부 VARCHAR(10),
    계약내용 TEXT,
    PRIMARY KEY (접수번호) 
);