CREATE TABLE IF NOT EXISTS dart.fn_sgl_acct_all (
    _ts timestamptz NOT NULL,
    사업연도 SMALLINT NOT NULL,
    보고서코드 SMALLINT NOT NULL,
    접수번호 VARCHAR(14) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    개별연결구분 CHAR(3) NOT NULL,
    재무제표구분 VARCHAR(3) NOT NULL,
    재무제표명 VARCHAR(255),
    계정id VARCHAR(255),
    계정명 VARCHAR(255),
    계정상세 VARCHAR(255),
    당기명 VARCHAR(255),
    당기금액 BIGINT,
    당기누적금액 BIGINT,
    전기명 VARCHAR(255),
    전기금액 BIGINT,
    전기누적금액 BIGINT,
    전기분반기명 VARCHAR(255),
    전기분반기금액 BIGINT,
    전전기명 VARCHAR(255),
    전전기금액 BIGINT,
    정렬순서 SMALLINT,
    통화단위 VARCHAR(255)
);