CREATE TABLE IF NOT EXISTS dart.br_exec_stat (
    _ts timestamptz NOT NULL,
    사업연도 SMALLINT NOT NULL,
    보고서코드 SMALLINT NOT NULL,
    접수번호 VARCHAR(14) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    법인구분 CHAR(1),
    법인명 VARCHAR(255),
    성명 VARCHAR(255),
    성별 CHAR(1),
    출생년월 VARCHAR(200),
    직위 VARCHAR(255),
    등기임원여부 VARCHAR(255),
    상근여부 VARCHAR(255),
    담당업무 VARCHAR(255),
    주요경력 TEXT,
    최대주주관계 VARCHAR(255),
    재직기간 VARCHAR(255),
    임기만료일 VARCHAR(255)
);