CREATE TABLE IF NOT EXISTS dart.km_disposal_stock (
  _ts timestamptz NOT NULL,
  접수번호 VARCHAR(14) NOT NULL,
  법인구분 CHAR(1) NOT NULL,
  고유번호 VARCHAR(8) NOT NULL,
  회사명 VARCHAR(100) NOT NULL,
  처분예정보통주수 BIGINT,
  처분예정기타주수 BIGINT,
  처분대상보통주가격 BIGINT,
  처분대상기타주가격 BIGINT,
  처분예정보통주총액 BIGINT,
  처분예정기타주총액 BIGINT,
  처분예정시작일 DATE,
  처분예정종료일 DATE,
  처분목적 TEXT,
  시장매도량 BIGINT,
  시간외대량매매량 BIGINT,
  장외처분량 BIGINT,
  기타처분량 BIGINT,
  위탁투자중개업자 VARCHAR(300),
  처분전보통주식취득량_배당가능범위내 BIGINT,
  처분전보통주식취득비율_배당가능범위내 DECIMAL(10,2),
  처분전기타주식취득량_배당가능범위내 BIGINT,
  처분전기타주식취득비율_배당가능범위내 DECIMAL(10,2),
  처분전보통주식취득량_기타취득 BIGINT,
  처분전보통주식취득비율_기타취득 DECIMAL(10,2),
  처분전기타주식취득량_기타취득 BIGINT,
  처분전기타주식취득비율_기타취득 DECIMAL(10,2),
  처분결정일 DATE,
  사외이사참석수 SMALLINT,
  사외이사불참수 SMALLINT,
  감사위원참석여부 VARCHAR(10),
  일보통주매도한도량 INT,
  일기타주매도한도량 INT,
    PRIMARY KEY (접수번호) 
);