CREATE TABLE IF NOT EXISTS dart.km_spinoff_firm (
    _ts timestamptz NOT NULL,
    접수번호 CHAR(14) NOT NULL,
    법인구분 CHAR(1) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    회사명 VARCHAR(300) NOT NULL,
    분할방법 TEXT,
    분할중요영향및효과 TEXT,
    분할비율 TEXT,
    이전사업및재산내용 TEXT,
    존속회사명 VARCHAR(300),
    존속회사_자산총계 BIGINT,
    존속회사_부채총계 BIGINT,
    존속회사_자본총계 BIGINT,
    존속회사_자본금 BIGINT,
    존속회사_재무기준일 DATE,
    존속회사_최근사업연도매출액 BIGINT,
    존속회사_주요사업 VARCHAR(300),
    존속회사_상장유지여부 VARCHAR(10),
    분할회사명 VARCHAR(300),
    분할회사_자산총계 BIGINT,
    분할회사_부채총계 BIGINT,
    분할회사_자본총계 BIGINT,
    분할회사_자본금 BIGINT,
    분할회사_재무기준일 DATE,
    분할회사_최근사업연도매출액 BIGINT,
    분할회사_주요사업 TEXT,
    분할회사_재상장신청여부 VARCHAR(10),
    감자비율 VARCHAR(100),
    구주권제출시작일 DATE,
    구주권제출종료일 DATE,
    매매거래정지예정시작일 DATE,
    매매거래정지예정종료일 DATE,
    신주배정조건 TEXT,
    주주주식수비례여부및사유 TEXT,
    신주배정기준일 DATE,
    신주권교부예정일 DATE,
    신주상장예정일 DATE,
    주총예정일 DATE,
    채권자이의제출시작일 DATE,
    채권자이의제출종료일 DATE,
    분할기일 DATE,
    분할등기예정일 DATE,
    이사회결의일 DATE,
    사외이사참석수 SMALLINT,
    사외이사불참수 SMALLINT,
    감사위원참석여부 VARCHAR(10),
    풋옵션등계약체결여부 VARCHAR(10),
    계약내용 TEXT,
    증권신고서제출대상여부 VARCHAR(10),
    제출면제사유 VARCHAR(300),
    PRIMARY KEY (접수번호) 
);