CREATE TABLE IF NOT EXISTS dart.br_emp_stat (
    _ts timestamptz NOT NULL,
    사업연도 SMALLINT NOT NULL,
    보고서코드 SMALLINT NOT NULL,
    접수번호 VARCHAR(14) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    법인구분 CHAR(1),
    법인명 VARCHAR(255),
    사업부문 VARCHAR(255),
    성별 VARCHAR(2),
    개정전정규직수 BIGINT,
    개정전계약직수 BIGINT,
    개정전기타직원수 BIGINT,
    정규직수 BIGINT,
    정규직단시간근로자수 BIGINT,
    계약직수 BIGINT,
    계약직단시간근로자수 BIGINT,
    합계 BIGINT,
    평균근속연수 VARCHAR(200),
    연간급여총액 BIGINT,
    평균급여액 BIGINT,
    비고 TEXT,
    PRIMARY KEY (접수번호, 사업부문, 성별)
);