CREATE TABLE IF NOT EXISTS dart.fn_mult_acct (
    _ts timestamptz NOT NULL,
    사업연도 SMALLINT NOT NULL,
    보고서코드 SMALLINT NOT NULL,
    접수번호 VARCHAR(14) NOT NULL,
    고유번호 CHAR(8) NOT NULL,
    종목코드 VARCHAR(6),
    계정명 VARCHAR(255),
    개별연결구분 VARCHAR(3),
    개별연결명 VARCHAR(255),
    재무제표구분 CHAR(2),
    재무제표명 VARCHAR(255),
    당기명 VARCHAR(255),
    당기일자 VARCHAR(255),
    당기금액 BIGINT,
    당기누적금액 BIGINT,
    전기명 VARCHAR(255),
    전기일자 VARCHAR(255),
    전기금액 BIGINT,
    전기누적금액 BIGINT,
    전전기명 VARCHAR(255),
    전전기일자 VARCHAR(255),
    전전기금액 BIGINT,
    정렬순서 INT,
    통화단위 VARCHAR(255),
    PRIMARY KEY (접수번호, 정렬순서)
);