CREATE TABLE IF NOT EXISTS dart.km_capbns_increase (
    _ts timestamptz NOT NULL,
    접수번호 VARCHAR(14),
    법인구분 CHAR(1),
    고유번호 VARCHAR(8),
    회사명 VARCHAR(100),
    유상증자_신주_보통주식수 BIGINT,
    유상증자_신주_기타주식수 BIGINT,
    유상증자_주당액면가 INT,
    유상증자전보통주식총수 BIGINT,
    유상증자전기타주식총수 BIGINT,
    유상증자_시설자금 BIGINT,
    유상증자_영업양수자금 BIGINT,
    유상증자_운영자금 BIGINT,
    유상증자_채무상환자금 BIGINT,
    유상증자_타법인증권취득자금 BIGINT,
    유상증자_기타자금 BIGINT,
    유상증자방식 TEXT,
    무상증자_신주_보통주식수 BIGINT,
    무상증자_신주_기타주식수 BIGINT,
    무상증자_주당액면가 INT,
    무상증자전보통주식총수 BIGINT,
    무상증자전기타주식총수 BIGINT,
    무상증자_신주배정기준일 DATE,
    무상증자_주당보통주배정수 BIGINT,
    무상증자_주당기타주배정수 BIGINT,
    무상증자_신주배당기산일 DATE,
    무상증자_신주권교부예정일 DATE,
    무상증자_신주상장예정일 DATE,
    무상증자_이사회결의일 DATE,
    무상증자_사외이사참석수 SMALLINT,
    무상증자_사외이사불참수 SMALLINT,
    무상증자_감사위원참석여부 CHAR(100),
    공매도해당여부 CHAR(1),
    공매도시작일 DATE,
    공매도종료일 DATE,
    PRIMARY KEY (접수번호) 
);